config/routes.rb
FestivalPlanner::Application.routes.draw do
  get "welcome/index"
  resources :acts
  
  root 'welcome#index'

  

end

app/models/act.rb
class Act < ActiveRecord::Base
  validates_presence_of :name, :time, :stage
end

app/controllers/acts_controller.rb
class ActsController < ApplicationController
  before_filter :authenticate
  def edit
    @act = Act.find(params[:id])
  end
  def update
    @act = Act.find(params[:id])
    if @act.update(act_params)
      redirect_to root_path, notice: 'Act was successfully updated.'
    else
      redirect_to root_path, notice: 'Act was not successfully updated. :('
    end
  end
  def create
    @act = Act.new(act_params)
    if @act.save
      redirect_to root_path, notice: 'Act was successfully created.'
    else
      render action: 'index'
    end
  end
  def destroy
    @act = Act.find(params[:id])
    @act.destroy
    redirect_to root_path, notice: 'Act was successfully destroyed.'
  end
  def index
    @act = Act.new
  end
  private
    def act_params
      params[:act].permit!
    end
  protected
  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == "admin" && password == "password"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @acts = Act.all.order("time")
  end
end

app/helpers/acts_helper.rb
module ActsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/acts/create.html.erb
<h1>Addnew#create</h1>
<p>Find me in app/views/addnew/create.html.erb</p>

app/views/acts/edit.html.erb
<h1>Edit Act</h1>
<%= simple_form_for @act, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name, input_html: { value: @act.name } %>
  <%= f.input :time, input_html: { value: @act.time }, :hint => "Format 13:00 (24-Hour)" %>
  <%= f.input :stage, input_html: { value: @act.stage } %>
  <% if @act.want_to_see %>
    <%= f.input :want_to_see, input_html: { value: '1' }, :as => :boolean %>
  <% else %>
    <%= f.input :want_to_see, :as => :boolean %>
  <% end %>
  <%= f.button :submit %>
<% end %>

app/views/acts/index.html.erb
<h1>Create New Act</h1>
<%= simple_form_for @act, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :time, :hint => "Format 13:00 (24-Hour)" %>
  <%= f.input :stage %>
  <%= f.input :want_to_see, :as => :boolean %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Home", root_path, :class => 'brand' %>
<ul class="nav">
    <li>
    <%= link_to('Add New Act', acts_path) %>
    </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Festival Planner" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails application to plan times for a festival." %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <main role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <% if notice %>
                <div class="alert alert-success fade in" data-alert="alert">
                  <a class="close" data-dismiss='alert' href="#">×</a>
                  <p><%= notice %></p>
                </div>
              <% end %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </main>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Festival Acts</h1>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Time</th>
      <th>Stage</th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @acts.each do |act| %>
      <% if act.want_to_see %>
        <tr class="success">
      <% else %>
        <tr>
      <% end %>
          <td><%= act.name %></td>
          <td><%= act.time %></td>
          <td><%= act.stage %></td>
          <td><%= link_to 'Edit', edit_act_path(act) %></td>
          <td><%= link_to 'Delete', act, :data => { :confirm => 'Are you sure?' }, :method => :delete %></td>
        </tr>
    <% end %>
  </tbody>
</table>